spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bootcamp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

aws:
  s3:
    region: us-east-1
    bucket: avatares
    endpoint: http://localstack:4566
    public-url: http://localhost:4566
    accessKey: test
    secretKey: test

app:
  jwt:
    secret: "V74gRdzyIA5/qeh1dFdUmfsKbV3pSPqQTT/zXGYBNGY="
    expiration-ms: 86400000

default:
  avatar: http://localhost:4566/avatares/defaults/default-avatar.png

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    com.ProjectExperience.api: DEBUG
